---
deployment:
  tasks:
    - /bin/cd /home/askabent/repositories/Afinju
    - export PATH=/opt/cpanel/ea-nodejs20/bin:$PATH
    - npm ci
    - npm run build
    - /bin/mkdir -p /home/askabent/public_html
    - /bin/cp -R dist/. /home/askabent/public_html/
